#https://github.com/anita-russo/
language: node_js

node_js:
  - "10.9.0"

cache: npm

before_install:
  - ls -la
  - mkdir dist
  - cd dist
  - ls

install:
  - ls -la
  - sudo npm install
  - ls -la
